# Generated by Django 4.1.6 on 2023-02-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
