# Generated by Django 4.1.6 on 2023-02-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0003_node_x_pos_node_y_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='shape',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
